[build]
  publish = "public"
  functions = "netlify/functions"

[functions]
  node_bundler = "esbuild"

[[redirects]]
  from = "/api/submit"
  to = "/.netlify/functions/submit"
  status = 200

[[redirects]]
  from = "/api/admin/login"
  to = "/.netlify/functions/admin-login"
  status = 200

[[redirects]]
  from = "/api/admin/applications"
  to = "/.netlify/functions/admin-applications"
  status = 200

[[redirects]]
  from = "/api/admin/delete"
  to = "/.netlify/functions/admin-delete"
  status = 200

[[redirects]]
  from = "/admin"
  to = "/admin.html"
  status = 200


[[redirects]]
  from = "/api/application-status"
  to = "/.netlify/functions/application-status"
  status = 200

[[redirects]]
  from = "/api/admin/update-status"
  to = "/.netlify/functions/admin-update-status"
  status = 200
